name: catcher
description: Plugin for error catching which provides multiple handlers for
  dealing with errors when they are not caught by the developer.
version: 0.7.0
homepage: https://github.com/jhomlala/catcher

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  device_info_plus: ^8.0.0
  device_info_plus_platform_interface: ^7.0.0
  dio: ^4.0.1
  flutter:
    sdk: flutter
  flutter_mailer: ^2.0.0
  flutter_web_plugins:
    sdk: flutter
  fluttertoast: ^8.0.8
  logger: null
  logging: ^1.0.2
  mailer: ^5.0.2
  package_info_plus: null
  sentry: ^6.1.0
  universal_io: ^2.0.4

dev_dependencies:
  lint: ^1.7.2
  stack_trace: ^1.11.0

flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.catcher
        pluginClass: CatcherPlugin
      ios:
        pluginClass: CatcherPlugin
      web:
        pluginClass: CatcherWebPlugin
        fileName: catcher_web_plugin.dart
      macos:
        pluginClass: CatcherPlugin
      windows:
        pluginClass: CatcherPlugin
      linux:
        pluginClass: CatcherPlugin
